Log Tab and pulling in everyone's branches
codieorberson/NVSHR pull request #28
Opened 2019-11-05 03:48 UTC by codieorberson

Updated Log tab of the Gui with a button that will display the logfile.txt file when clicked

2019-11-05 04:14 UTC, lgint8042 reviewed
My computer doesn't recognize the `notepad.exe` command being sent. Is this a Windows specific one?

2019-11-05 05:19 UTC, codieorberson commented
Just updated it. Try now

2019-11-12 21:43 UTC, jcf1991 approved these changes
Let's merge this.

2019-11-13 16:23 UTC, lgint8042 commented on blinkDetector.py
> +            # the six points on the eyes, particularly when they move off
This comment needs to be updated.

2019-11-13 16:24 UTC, lgint8042 commented on databaseManager.py
> +    "palm, STOP, Alexa\n"
All of the things linked to the database should NOT have "on/off" linked to them. It should just have the smart home device it is linked to.

2019-11-13 16:25 UTC, lgint8042 commented on fileManager.py
> +            os.remove(self._file_name)
This function needs to be looked at again. Why are we removing the file from the OS when we want to save that information? Doesn't make sense.

2019-11-13 16:27 UTC, lgint8042 commented on gestureParser.py
> +            self.Tp_Link_Devices.turn_on_off(gesture_sequence)
Why wouldn't we try and pass the smart home device to it other than the gesture sequence? I think all of that is held within the databse manager and can be accessed if we add it in?

2019-11-13 16:29 UTC, lgint8042 commented on guiManager.py
>      "tab4": {"title": "Log",
Can we add some text to this tab to explain the button and what it does? If needed, I can add it in.

2019-11-13 16:30 UTC, lgint8042 commented on guiManager.py
> +                self.delete_log_file()
Are deleting it after we open it? Couldn't we move this line into the open_log_file() method and just delete it before it opens so that way it is updated correctly?

2019-11-13 16:31 UTC, lgint8042 commented on guiManager.py
> +import platform
Is this import still being used? If not, it needs to be deleted.

2019-11-13 16:35 UTC, lgint8042 commented on popUp.py
> +def _catch_transition_exception(exception, value, traceback):
I still am not a fan of this. Why are putting something into our code that throws errors so much that we have to catch them? Especially for something that is not actually needed for what we are trying to complete with this first iteration. I still firmly believe it is not needed and should be removed. We need to vote on whether or not this is worth it at todays meeting. Is there also not any other way to do what you want? I feel like this will not be liked by him very much because it's, again, something not needed.

2019-11-13 16:35 UTC, lgint8042 commented on popUp.py
> +        self.center(400, 200, self.popup.winfo_screenwidth(), self.popup.winfo_screenheight())
This needs to be 400, 300

2019-11-13 16:36 UTC, lgint8042 commented on processManager.py
> +import multiprocessing
Did you read Eric's comments on the SDD? He has some questions that need to be addressed for this module in particular.

2019-11-13 16:38 UTC, lgint8042 commented on smartHomeActivator.py
> +# import homeassistant
Is this file even still needed? I thought Codie said we weren't using homeassistant anymore? If Codie has it working with his other files, we should delete this because it won't be used.

2019-11-13 16:39 UTC, lgint8042 commented on smartHomeProcessManager.py
> +import multiprocessing
I would make sure Eric's comments are addressed for both of the ProccessManagers.

2019-11-13 16:41 UTC, lgint8042 commented on databaseManager.py
> +    "palm, STOP, Alexa\n"
Look at the GUI menus for the devices we have listed and how they are listed. I think I updated this on my branch.

2019-11-13 16:42 UTC, lgint8042 requested changes
Please see my comments.

2019-11-15 21:38 UTC, lgint8042 commented on fileManager.py
> +            os.remove(self._file_name)
I fixed this on my branch.

2019-11-15 21:38 UTC, lgint8042 commented on guiManager.py
>      "tab4": {"title": "Log",
Spark is working on changing this, so I am going to resolve this comment.

2019-11-15 23:34 UTC, lgint8042 commented on smartHomeActivator.py
> +                index += 1
Can you add in something to check to see if it's actually connected to the devices? And then print something to the log that says it's not or is?

2019-11-15 23:34 UTC, lgint8042 commented on nonVerbalSmartHomeRecognitionSystem.py
> -        self.smart_home_activator = SmartHomeActivator()
Can you explain why this was moved? Does it change the way the add_command works? Is there a way to keep it how it was and still do what you need it do?

2019-11-16 00:01 UTC, codieorberson commented on smartHomeActivator.py
> +                index += 1
Will do

2019-11-16 02:39 UTC, codieorberson commented on smartHomeProcessManager.py
> +import multiprocessing
Deleted this file

2019-11-16 03:01 UTC, lgint8042 approved these changes

2019-11-16 21:23 UTC, merged