Merge master
codieorberson/NVSHR pull request #29
Opened 2019-11-14 04:02 UTC by jcf1991

Latest changes from all branches as of November 13th.

2019-11-14 13:52 UTC, lgint8042 commented on modules/dataManager.py
> +    "fist-palm-blink, 192.168.1.197, Smart Plug\n",
What is this? I had it changed to what it needed to be to match with the command menu stuff on mine. Is there a reason this was changed to be like this? Also we should have one command for both the on/off. There shouldn't be two different commands for on and off.

2019-11-14 13:53 UTC, lgint8042 commented on modules/data_manager/fileManager.py
> +            os.remove(self._file_name)
We still need to figure out this remove function call and why it is there.

2019-11-14 13:54 UTC, lgint8042 commented on modules/gestureSequenceDetector.py
> +
Unneeded spaces

2019-11-14 14:02 UTC, lgint8042 commented on modules/guiManager.py
> +
Unneeded spaces

2019-11-14 14:02 UTC, lgint8042 commented on modules/guiManager.py
> +
Unneeded spaces

2019-11-14 14:11 UTC, lgint8042 commented on modules/gesture_sequence_detector/gesture_detector/multithreadedPerimeter.py
> +    def reset(self):
Does this have to do with Eric's comments?

2019-11-14 14:13 UTC, lgint8042 commented on modules/gui_manager/guiLayout.py
> +#                    "format": "device_selection"
???

2019-11-14 14:14 UTC, lgint8042 commented on modules/gui_manager/guiLayout.py
> +                    "format": "field"
???

2019-11-14 14:14 UTC, lgint8042 commented on modules/gui_manager/tab.py
> +            elif element["format"] == "field":
What is this used for? Why was it added?

2019-11-14 14:15 UTC, lgint8042 commented on modules/gui_manager/tab.py
> +            elif element["format"] == "device_selection":
We shouldn't need this. We can just hard code it based on the device that is chosen.

2019-11-14 14:16 UTC, lgint8042 commented on modules/gui_manager/tab.py
> +                for option in self.command_manager.action:
If you pulled my changes, this should be different. It is not consistent with the changes on everyone's branches even though that is what you claimed.

2019-11-14 14:18 UTC, lgint8042 commented on modules/gui_manager/tab.py
> +                for option in self.command_manager.action:
Where are the actual devices? All I see is the smart plug and Alexa, which we have more. Why was this changed when it didn't need to be? You also didn't consult me on changing it even though I have been working on it for the past couple of weeks.

2019-11-14 14:19 UTC, lgint8042 commented on modules/gui_manager/tab.py
> +            if x in range(len(self.command_manager.action)) and value == self.command_manager.action[x] and value != "None":
Again, I was working on this and you made changes that you didn't ask me about. You shouldn't be pulling in everyone's changes on their branch when they aren't finished and changing things when you want to without asking people about it!

2019-11-14 14:20 UTC, lgint8042 commented on modules/gui_manager/tab.py
> +            if self.new_command[0].get() != self.new_command[1].get() and self.new_command[1].get() != self.new_command[
Same comment as the one above it. STOP MAKING CHANGES TO THINGS PEOPLE ARE STILL WORKING ON.

2019-11-14 14:20 UTC, lgint8042 commented on modules/logger.py
> +        os.remove(_file_name)
Again, what is the point of this?

2019-11-14 14:21 UTC, lgint8042 commented on modules/popUp.py
> +def _catch_transition_exception(exception, value, traceback):
This is still weird to me. Don't know why we want to keep something that throws errors that we have to catch when it's not needed.

2019-11-14 14:22 UTC, lgint8042 commented on modules/processManager.py
> +import multiprocessing
Have you tried to address Eric's concerns in this?

2019-11-14 14:23 UTC, lgint8042 commented on modules/smartHomeActivator.py
> +                self.sound_player.speak("Unable to communicate with Smart Plug at " + ip_address)
Where did we say it would speak anything? It should just play a failure sound.

2019-11-14 14:24 UTC, lgint8042 commented on modules/smart_home_activator/smartHomeProcessManager.py
> +    #On Windows, we use the previously defined kludge.
"On other operating systems"

2019-11-14 14:24 UTC, lgint8042 commented on modules/smart_home_activator/smartPlugManager.py
> +from pyHS100 import SmartPlug # pip3 insrtall pyhs100
"install"

2019-11-14 14:25 UTC, lgint8042 commented on modules/soundPlayer.py
> +    def speak(self, text):
Still confused where we said this was going to be happening?

2019-11-14 14:26 UTC, lgint8042 commented on modules/sound_player/subprocessExecutor.py
> +    def __clean_up_subprocesses__(self):
Is this where you are addressing Eric's comments?

2019-11-14 14:27 UTC, lgint8042 commented on test-files/gestureDetectorTest.py
> +    detector.trigger_events(timestamp, 4, fist_perimeter, palm_perimeter, left_eye_perimeter, right_eye_perimeter)
This needs to stay at 400.

2019-11-14 14:32 UTC, lgint8042 requested changes
This is not what I wanted when I said that you needed to make a PR for your changes. It SHOULD NOT have everyone's changes from their branch. I know I had things that were not DONE on my branch and now there are a lot of changes that need to be made 1) because you merged things that weren't done and 2) because you merged those things, you changed things that were still being worked on (which you shouldn't have done without communicating your concerns) so now I will need to spend MORE TIME making all sure all of my changes are correct and the way I had them. I just wanted YOUR changes. PRs are for your INDIVIDUAL changes not EVERYONES. We have less than a week to make sure everything is correct AND do a test cycle and this is making everyone's life HARDER. This is a TEAM project and this is not helping the team in ANY WAY other than making us have to do more work because we have to make our changes AGAIN because you didn't capture them in your PR.

2019-11-16 06:59 UTC, jcf1991 commented on modules/dataManager.py
> +    "fist-palm-blink, 192.168.1.197, Smart Plug\n",
Codie's SmartPlus needs an IP address that is configurable by the admin. Ideally we would have two classes of smart home objects now, but we have to store the IP somewhere that can be changed by the admin.

2019-11-16 07:02 UTC, jcf1991 commented on modules/gui_manager/tab.py
> +            elif element["format"] == "field":
I need a place for the admin to input voice commands and IP addresses. Otherwise this is a toy without any real applications.

2019-11-16 07:03 UTC, jcf1991 commented on modules/gesture_sequence_detector/gesture_detector/multithreadedPerimeter.py
> +    def reset(self):
Nah, it's just a convenience method.

2019-11-16 07:05 UTC, jcf1991 commented on modules/gui_manager/tab.py
> +                for option in self.command_manager.action:
Wemo exists as a file, but isn't used in the rest of the codebase on any branch AFAIK. What devices are you thinking of?

2019-11-16 07:10 UTC, jcf1991 commented on modules/gui_manager/tab.py
> +            if self.new_command[0].get() != self.new_command[1].get() and self.new_command[1].get() != self.new_command[
Why are you typing like an angry child? Does this seem professional? You aren't treating this project seriously. I had to fight you guys on having persistent data and not making the user click a button before entering commands, literally going to Iqbal for "clarification." You thought a 4-tab GUI was too time-consuming to work on. I don't want to work around you to get things done, but you aren't doing the things that I need to have a reasonable project.

2019-11-16 07:12 UTC, jcf1991 commented on modules/logger.py
> +        os.remove(_file_name)
It puts a fragile piece of data that might change at some point into one specific place. If we want to change that file name we can do it one place instead of many. It's a generally good practice.

2019-11-16 07:15 UTC, jcf1991 commented on modules/popUp.py
> +def _catch_transition_exception(exception, value, traceback):
We need to have this run on startup. I like waiting to launch the processor-intensive GUI, but I'd rather launch it immediately than block the main function of our system until a button is clicked. Please, let me have a functional system. Either tear out the pop up, accept the error catch, or find a better way of transitioning. Let me detect gestures on start up. It's, like, super impirtant. You're NERFing my system here.

2019-11-16 07:16 UTC, jcf1991 commented on modules/processManager.py
> +import multiprocessing
I don't think his concerns are too worrisome, I replied to his comment. In short, we're not running too many processes at once and we're cleaning up after ourselves appropriately.

2019-11-16 07:20 UTC, jcf1991 commented on modules/smartHomeActivator.py
> +                self.sound_player.speak("Unable to communicate with Smart Plug at " + ip_address)
Read the context of the code. This is playing when a gesture sequence is registered, but a smart plug could not be found at the IP address specified by the admin. How *should* we handle this? The same feedback as an unrecognised gesture sequence is misleading, it would make the user think they're inputting a command incorrectly instead of letting them know that there's an upstream technical error (the plug not being plugged in, or it reseting its IP address, or whatever).

2019-11-16 07:31 UTC, jcf1991 commented on test-files/gestureDetectorTest.py
> +    detector.trigger_events(timestamp, 4, fist_perimeter, palm_perimeter, left_eye_perimeter, right_eye_perimeter)
That change was made by you: https://github.com/codieorberson/NVSHR/commit/e2ad95a4a51dc233bc5c4b06f9d751914a5c5a5b#diff-6b7e5ad57e3586720c1ac839f7471cc5

The tests still don't run on Linux despite it being our target platform, muh dude. I know I'm gonna have to write a bunch after the code freeze, but right now I'm just merging changes from you and Danielle. My username is nowhere in the history of that file.

2019-11-16 07:32 UTC, jcf1991 commented on modules/sound_player/subprocessExecutor.py
> +    def __clean_up_subprocesses__(self):
Nope, separate, new file. The sounds are playing synchronously right now, blocking everything else while they play. It's totally unacceptable. This is ugly, but it addresses that.

2019-11-16 13:58 UTC, lgint8042 commented on modules/dataManager.py
> +    "fist-palm-blink, 192.168.1.197, Smart Plug\n",
After speaking with Codie yesterday, I found that information out. However, Codie and I talked about just hard coding in those IP addresses for right now and not adding that functionality to the system because it won't be changing in this first iteration.

2019-11-16 14:02 UTC, lgint8042 commented on modules/gui_manager/tab.py
> +            if self.new_command[0].get() != self.new_command[1].get() and self.new_command[1].get() != self.new_command[
I was angry because a lot of my changes that I spent a reasonable amount of time doing didn't seem to be in your code. It is a concern a lot of people in the group have had and it is upsetting to see your hard work just changed. I am also taking this project very seriously. I am trying to make this project the best it can be within reason. This comment seems very centered around how YOU want the system to look and not how the TEAM wants the system to work. It is a group project, so the groups opinion needs to be taken into consideration. You are not working around me personally, when other people in the group feel the same way.

2019-11-16 14:06 UTC, lgint8042 commented on modules/popUp.py
> +def _catch_transition_exception(exception, value, traceback):
Again, this is not YOUR system. This is the GROUPS system. The way it is set up in this PR, it throws so many errors on start up that it crashes the system. There are, again, other people in the group that do not like this part as well and they have made it known they don't. I am not the only one who feels that way.

2019-11-16 14:09 UTC, lgint8042 commented on test-files/gestureDetectorTest.py
> +    detector.trigger_events(timestamp, 4, fist_perimeter, palm_perimeter, left_eye_perimeter, right_eye_perimeter)
I'm still not sure where you are getting that Linux is our target platform when it is explicitly never mentioned in the SRS that was copied into the final documentation file. I have also told you multiple times that I am not sure why the tests don't run on your computer when I am using built in Python testing libraries. Others have had issues that were resolved by them moving the test files out of the folder they are currently in and running them.

2019-11-17 02:28 UTC, jcf1991 commented on test-files/gestureDetectorTest.py
> +    detector.trigger_events(timestamp, 4, fist_perimeter, palm_perimeter, left_eye_perimeter, right_eye_perimeter)
Cuz it's supposed to run on a Pi, or similar available hardware. Those don't typically rock Windows or OSX.

I posted output in slack of getting errors after moving the files as suggested. It claimed there were syntax errors, not import errors. Don't worry, I'll fix your tests after the freeze. It just *is* hypocritical for you to complain about things not running on your system, given that you never fixed the tests.

2019-11-17 02:29 UTC, jcf1991 commented on modules/dataManager.py
> +    "fist-palm-blink, 192.168.1.197, Smart Plug\n",
Well that wouldn't be usable for anyone else at all. Wouldn't you rather it be usable, like I made it?

2019-11-17 02:35 UTC, jcf1991 commented on modules/gui_manager/tab.py
> +                for option in self.command_manager.action:
It can't be *consistent* with *all* changes -- even if I didn't change a thing you would still be stepping over each other's toes. Part of pulling in changes is making them work together. With the exception of your tests, which I can't run, I've been running the code and attempting to preserve the functionality between branches.  Between Codie's code and mine, I need a couple of options present.

2019-11-17 02:46 UTC, jcf1991 commented on modules/gui_manager/tab.py
> +            if self.new_command[0].get() != self.new_command[1].get() and self.new_command[1].get() != self.new_command[
When you type in all caps you aren't treating a situation seriously. When I have to ask the professor if we need persistent data despite that being a requirement from the beginning you aren't taking a project seriously, you're trying to get by with minimal effort and inadvertently throwing roadblocks up in the way of those who actually produce.

2019-11-17 02:53 UTC, jcf1991 commented on modules/popUp.py
> +def _catch_transition_exception(exception, value, traceback):
The pop-up window blocking execution is one of two worst features of master right now, the other being synchrous audio. These things make the system less usable. I'm only one voice, but I happen to be the correct voice here. There is no use case for this product that is made better by not running the main loop on system startup. Making it more usable is trivial, we just have to *not* do what you're doing.

2019-11-20 21:08 UTC, closed without merging